spring.application.name=ai-assistant-service
# MCP client config
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
spring.ai.mcp.client.toolcallback.enabled=false

# Server port
server.port=8098